### ISSUE TITLE
AddButton does not work because Buttons is null

### ISSUE THREAD

**Issue by SrLicht** [UncomplicatedCustomServer/SimpleDiscord#5]
Activitiy buttons are null by default

https://github.com/UncomplicatedCustomServer/SimpleDiscord/blob/1d359d1295769df955993f82101b17bd80f9d630/SimpleDiscord/Components/Builders/ActivityBuilder.cs#L6-L8
https://github.com/UncomplicatedCustomServer/SimpleDiscord/blob/1d359d1295769df955993f82101b17bd80f9d630/SimpleDiscord/Components/Activity.cs#L3-L6

So doing this will cause ``System.ArgumentNullException: Value cannot be null.
                                 Parameter name: source
                                   at System.Linq.Enumerable.Append[TSource]``
https://github.com/UncomplicatedCustomServer/SimpleDiscord/blob/1d359d1295769df955993f82101b17bd80f9d630/SimpleDiscord/Components/Builders/ActivityBuilder.cs#L46-L50

**Comment by FoxWorn3365** [comment]
We will fix, thank you for the bug report.
Next time please ping me on the UCS Discord server so I can see this asap

**Comment by FoxWorn3365** [comment]
fixed in the latest pr #6
